name: CI
on:
  # - pull_request
  - push
jobs:
  build_posix:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:
          - '8.8.3'
          - '8.6.5'
          - '8.4.4'
          - '8.2.2'
        cabal:
          - '3.2'
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Cache cabal-store
        uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libgtk2.0-dev
      - name: Install system dependencies
        if: runner.os == 'macOS'
        run: brew install gcc@9 gtk+ pkg-config
      - name: Set extra cabal build options for macOS
        if: runner.os == 'macOS'
        run: echo "::set-env name=CABAL_BUILD_OPTIONS::--constraint='gtk +have-quartz-gtk' --with-gcc=gcc-9"
      - name: Build Haskell dependencies
        run: |
          echo $CABAL_BUILD_OPTIONS
          eval cabal build $CABAL_BUILD_OPTIONS --enable-tests --enable-benchmarks --dep -j all
          eval cabal build $CABAL_BUILD_OPTIONS --disable-tests --disable-benchmarks --dep -j all
      - name: Build ThreadScope
        run: |
          DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
          # Packaging...
          cabal sdist all
          # Unpacking...
          mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
          cd ${DISTDIR} || false
          find . -maxdepth 1 -type f -name '*.tar.gz' -exec tar -xvf '{}' \;
          find . -maxdepth 1 -type f -name '*.tar.gz' -exec rm       '{}' \;
          PKGDIR_threadscope="$(find . -maxdepth 1 -type d -regex '.*/threadscope-[0-9.]*')"
          # Generate cabal.project
          rm -rf cabal.project cabal.project.local cabal.project.freeze
          touch cabal.project
          echo "packages: ${PKGDIR_threadscope}" >> cabal.project
          for pkg in $($HCPKG list --simple-output); do
            echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(threadscope)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local;
          done
          cat cabal.project || true
          cat cabal.project.local || true
          # Building...
          # this builds all libraries and executables (without tests/benchmarks)
          eval cabal build $CABAL_BUILD_OPTIONS --disable-tests --disable-benchmarks all
          # Building with tests and benchmarks...
          # build & run tests, build benchmarks
          eval cabal build $CABAL_BUILD_OPTIONS --enable-tests --enable-benchmarks all
          # cabal check...
          (cd ${PKGDIR_threadscope} && cabal -vnormal check)
          # Building without installed constraints for packages in global-db...
          rm -f cabal.project.local
          eval cabal build $CABAL_BUILD_OPTIONS --disable-tests --disable-benchmarks all
      - name: Prepare Release
        run: |
          cp $(find dist-newstyle/ -type f -name threadscope -exec test -x {} \; -print) "threadscope.$PLATFORM.ghc-$GHCVER"
          gzip -f "threadscope.$PLATFORM.ghc-$GHCVER"
        env:
          GHCVER: ${{ matrix.ghc }}
          PLATFORM: ${{ matrix.os }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./threadscope.${{ matrix.os }}.ghc-${{ matrix.ghc }}.gz
          asset_name: threadscope.${{ matrix.os }}.ghc-${{ matrix.ghc }}.gz
          asset_content_type: application/gzip
  build_windows:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:
          - '8.8.3'
          - '8.6.5'
          - '8.4.4'
          - '8.2.2'
        cabal:
          - '3.2'
        os:
          - windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Setup MSYS2
        uses: eine/setup-msys2@v1
        with:
          update: true
          path-type: inherit
      - name: Cache cabal-store
        uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal
      - name: Install system dependencies
        run: msys2 pacman --noconfirm -Sy mingw-w64-x86_64-pkg-config mingw-w64-x86_64-gtk2
      - name: Build Haskell dependencies
        run: msys2 cabal build -j1 all --dep
      - name: Build ThreadScope
        run: msys2 cabal build -j1 all
      - name: Prepare Release
        run:
          bash -c "cp -v $(find -name threadscope.exe) ./threadscope.exe"
          7z a threadscope.windows.ghc-%GHCVER%.zip threadscope.exe
        env:
          GHCVER: ${{ matrix.ghc }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./threadscope.windows.ghc-${{ matrix.ghc }}.zip
          asset_name: threadscope.windows.ghc-${{ matrix.ghc }}.zip
          asset_content_type: application/zip
